[context.production.environment]
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="pk_live_Y2xlcmsubm9tYWR1bGUuY29tJA"
CLERK_SECRET_KEY="sk_live_StWOdu2FGg5DfRL9gdEKxUKEQW8dIiEcsiDuYQppa0"

[context.deploy-preview.environment]
NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY="pk_test_c3dlZXQtZ2F0b3ItOTYuY2xlcmsuYWNjb3VudHMuZGV2JA"
CLERK_SECRET_KEY="sk_test_qBl0F9ofL846F00h2prqUpqONqC9Io7ooFPJEl7WND"
